apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
  name: open-webui-static-secret
  namespace: owu-app
spec:
  destination:
    create: true
    name: open-webui-secrets
  mount: kv
  path: open-webui/oidc
  refreshAfter: 24h
  type: kv-v2
  vaultAuthRef: open-webui-vault-auth
