apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  annotations: {}
  name: vault-kv-app
  namespace: app
spec:
  destination:
    create: true
    name: secretkv
  mount: kv
  path: webapp/config
  refreshAfter: 30s
  type: kv-v2
  vaultAuthRef: static-auth
