apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  annotations: {}
  name: argocd-static-secret
  namespace: argo-cd-app
spec:
  destination:
    create: true
    name: github-repo
    labels:
      argocd.argoproj.io/secret-type: repository
  mount: kv
  path: argocd/repo-access
  refreshAfter: 24h
  type: kv-v2
  vaultAuthRef: argocd-vault-auth
