apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  annotations: {}
  name: argocd-static-secret
  namespace: argo-cd-app
spec:
  destination:
    create: true
    name: github-repo
    labels:
      argocd.argoproj.io/secret-type: repository
  mount: kv
  path: argocd/repo-access
  refreshAfter: 24h
  type: kv-v2
  vaultAuthRef: argocd-vault-auth
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  annotations: {}
  name: argocd-static-secret-oidc
  namespace: argo-cd-app
spec:
  destination:
    create: true
    name: argocd-oidc-secret
    labels:
      app.kubernetes.io/part-of: argocd #MUST HAVE THIS LABEL
  mount: kv
  path: argocd/oidc
  refreshAfter: 24h
  type: kv-v2
  vaultAuthRef: argocd-vault-auth
