# https://argo-cd.readthedocs.io/en/stable/user-guide/multiple_sources/#helm-value-files-from-external-git-repository
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: linkding
  namespace: argo-cd-app
spec:
  project: default
  sources:
  - repoURL: 'https://rubxkube.github.io/charts'
    chart: linkding
    targetRevision: 1.1.20
    helm:
      valueFiles:
      - $values/k8s_manifests/linkding/values.yaml

  - repoURL: https://github.com/fahmed24/homelab.git
    targetRevision: dev
    path: k8s_manifests/linkding
    ref: values

  destination:
    server: https://kubernetes.default.svc
    namespace: linkding-app
