apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultDynamicSecret
metadata:
  annotations: {}
  name: keycloak-dynamic-secret
  namespace: keycloak-app
spec:
  destination:
    create: true
    name: keycloak-secrets
  mount: prod-postgres
  path: creds/prod-keycloak-role
  rolloutRestartTargets:
    - kind: StatefulSet
      name: my-keycloak
  vaultAuthRef: keycloak-dynamic-auth
