apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-cloudflare-prod
  name: linkding
  namespace: linkding-app
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`linkding.fahmed.org`)
      middlewares: null
      services:
        - name: linkding
          port: 9090
