apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  annotations: {}
  name: linkding-oidc-static-secret
  namespace: linkding-app
spec:
  destination:
    create: true
    name: oidc-client-secret
  mount: kv
  path: linkding/oidc
  refreshAfter: 24h
  type: kv-v2
  vaultAuthRef: linkding-dynamic-auth
