apiVersion: v1
kind: ServiceAccount
metadata:
  annotations: {}
  name: linkding-app-sa
  namespace: linkding-app
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultAuth
metadata:
  annotations: {}
  name: linkding-dynamic-auth
  namespace: linkding-app
spec:
  kubernetes:
    audiences:
      - vault
    role: linkding-role
    serviceAccount: linkding-app-sa
  method: kubernetes
  mount: kubernetes
