apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"secrets.hashicorp.com/v1beta1","kind":"VaultStaticSecret","metadata":{"annotations":{},"name":"linkding-oidc-static-secret","namespace":"linkding-app"},"spec":{"destination":{"create":true,"name":"oidc-client-secret"},"mount":"kv","path":"linkding/oidc","refreshAfter":"24h","type":"kv-v2","vaultAuthRef":"linkding-dynamic-auth"}}
  creationTimestamp: "2026-01-27T00:13:51Z"
  finalizers:
  - vaultstaticsecret.secrets.hashicorp.com/finalizer
  generation: 2
  name: linkding-oidc-static-secret
  namespace: linkding-app
  resourceVersion: "8697572"
  uid: f14e7254-7683-4f14-80e4-c13b080710f0
spec:
  destination:
    create: true
    name: oidc-client-secret
    overwrite: false
    transformation: {}
  hmacSecretData: true
  mount: kv
  path: linkding/oidc
  refreshAfter: 24h
  type: kv-v2
  vaultAuthRef: linkding-dynamic-auth
