apiVersion: v1
kind: ConfigMap
metadata:
  annotations: {}
  name: coredns-custom
  namespace: kube-system
data:
  rewrite.override: |
    rewrite name auth.fahmed.org traefik.kube-system.svc.cluster.local
    rewrite name vault.fahmed.org my-vault.my-vault.svc.cluster.local
    #rewrite name loki.fahmed.org my-loki-gateway.loki-app.svc.cluster.local
    #rewrite name oauth2.fahmed.org traefik.kube-system.svc.cluster.local
