apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cluster-storage-downloads-pvc
  namespace: qbittorrent-vpn-app
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 18000Gi
  volumeName: cluster-storage-downloads-pv
  storageClassName: ""
