apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
  name: qbittorrent-vpn-static-secret
  namespace: qbittorrent-vpn-app
spec:
  destination:
    create: true
    name: wireguard-private-key
  mount: kv
  path: qbittorrent-vpn
  refreshAfter: 24h
  type: kv-v2
  vaultAuthRef: qbittorrent-vpn-vault-auth
