apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
  name: portfolio-certificate
  namespace: portfolio-app
spec:
  commonName: fahmed.org
  dnsNames:
    - fahmed.org
  duration: 2160h
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-cloudflare-prod
  renewBefore: 720h
  secretName: portfolio-tls
