tempo:
  extraEnv:
  - name: AWS_ACCESS_KEY_ID
    valueFrom:
      secretKeyRef:
        key: username
        name: tempo-secrets
  - name: AWS_SECRET_ACCESS_KEY
    valueFrom:
      secretKeyRef:
        key: password
        name: tempo-secrets
  metricsGenerator:
    enabled: true
    remoteWriteUrl: http://my-prometheus-server.prometheus-app.svc.cluster.local
  overrides:
    defaults:
      metrics_generator:
        processors:
        - service-graphs
        - span-metrics
        - local-blocks
  persistence:
    enabled: true
  storage:
    trace:
      backend: s3
      s3:
        bucket: tempo-storage
        endpoint: my-minio.minio-app.svc.cluster.local:9000
        insecure: true
        region: us-east-1
