apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
  name: tempo-sa
  namespace: tempo-app
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultAuth
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
  name: tempo-vault-auth
  namespace: tempo-app
spec:
  kubernetes:
    audiences:
      - vault
    role: minio-role
    serviceAccount: tempo-sa
  method: kubernetes
  mount: kubernetes
