apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  annotations: {}
  name: tempo-static-secret
  namespace: tempo-app
spec:
  destination:
    create: true
    name: tempo-secrets
  mount: kv
  path: minio
  refreshAfter: 24h
  type: kv-v2
  vaultAuthRef: tempo-vault-auth
