apiVersion: v1
kind: ServiceAccount
metadata:
  annotations: {}
  name: cert-manager-sa
  namespace: cert-manager
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultAuth
metadata:
  annotations: {}
  name: cert-manager-vault-auth
  namespace: cert-manager
spec:
  kubernetes:
    audiences:
      - vault
    role: cloudflare-role
    serviceAccount: cert-manager-sa
  method: kubernetes
  mount: kubernetes
