apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  annotations: {}
  name: cert-manager-static-secret
  namespace: cert-manager
spec:
  destination:
    create: true
    name: cloudflare-api-token
  mount: kv
  path: cloudflare
  refreshAfter: 24h
  type: kv-v2
  vaultAuthRef: cert-manager-vault-auth
