apiVersion: v1
kind: PersistentVolume
metadata:
  name: cluster-storage-pv-root
spec:
  capacity:
    storage: 230Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 192.168.68.57
    path: /export/cluster-storage

