driver:
  enabled: false
toolkit:
  enabled: true
  env:
  - name: CONTAINERD_SOCKET
    value: /run/k3s/containerd/containerd.sock
devicePlugin:
  config:
    name: time-slicing-config-all
    default: any
