apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  annotations: {}
  name: owu-certificate
  namespace: owu-app
spec:
  commonName: owu.fahmed.org
  dnsNames:
    - owu.fahmed.org
  duration: 2160h
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-cloudflare-prod
  renewBefore: 720h
  secretName: owu-tls
