apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  annotations: {}
  name: minio-static-secret
  namespace: loki-app
spec:
  destination:
    create: true
    name: loki-secrets
  mount: kv
  path: minio
  refreshAfter: 24h
  type: kv-v2
  vaultAuthRef: loki-vault-auth
