apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultDynamicSecret
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
  name: linkding-dynamic-secret
  namespace: linkding-app
spec:
  destination:
    create: true
    name: linkding-secrets
  mount: prod-postgres
  path: creds/prod-linkding
  rolloutRestartTargets:
    - kind: Deployment
      name: linkding
  vaultAuthRef: linkding-dynamic-auth
