apiVersion: v1
items:
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    creationTimestamp: "2025-12-22T23:43:49Z"
    name: default
    namespace: oauth2-proxy-app
    resourceVersion: "2602039"
    uid: f3f3b79b-d434-4b21-ad54-dbe37aed8049
- apiVersion: v1
  automountServiceAccountToken: true
  kind: ServiceAccount
  metadata:
    annotations:
      meta.helm.sh/release-name: my-oauth2-proxy
      meta.helm.sh/release-namespace: oauth2-proxy-app
    creationTimestamp: "2026-01-27T21:17:38Z"
    labels:
      app: oauth2-proxy
      app.kubernetes.io/component: authentication-proxy
      app.kubernetes.io/instance: my-oauth2-proxy
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/name: oauth2-proxy
      app.kubernetes.io/part-of: oauth2-proxy
      app.kubernetes.io/version: 7.13.0
      helm.sh/chart: oauth2-proxy-8.5.1
    name: my-oauth2-proxy
    namespace: oauth2-proxy-app
    resourceVersion: "8569124"
    uid: 295fe7f0-b8c4-4daf-85ca-71d33de0cf14
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","kind":"ServiceAccount","metadata":{"annotations":{},"name":"oauth2-proxy-sa","namespace":"oauth2-proxy-app"}}
    creationTimestamp: "2026-01-27T20:47:10Z"
    name: oauth2-proxy-sa
    namespace: oauth2-proxy-app
    resourceVersion: "8560220"
    uid: 6fddcb81-11f0-450f-8817-4a86ac01f0c6
- apiVersion: v1
  automountServiceAccountToken: true
  kind: ServiceAccount
  metadata:
    annotations:
      meta.helm.sh/release-name: public-oauth2-proxy
      meta.helm.sh/release-namespace: oauth2-proxy-app
    creationTimestamp: "2026-01-27T21:22:54Z"
    labels:
      app: oauth2-proxy
      app.kubernetes.io/component: authentication-proxy
      app.kubernetes.io/instance: public-oauth2-proxy
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/name: oauth2-proxy
      app.kubernetes.io/part-of: oauth2-proxy
      app.kubernetes.io/version: 7.13.0
      helm.sh/chart: oauth2-proxy-8.5.1
    name: public-oauth2-proxy
    namespace: oauth2-proxy-app
    resourceVersion: "8570717"
    uid: 0c122b83-0f03-4373-9e80-fe8ffcafb400
kind: List
metadata:
  resourceVersion: ""
