apiVersion: v1
items:
- apiVersion: secrets.hashicorp.com/v1beta1
  kind: VaultStaticSecret
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"secrets.hashicorp.com/v1beta1","kind":"VaultStaticSecret","metadata":{"annotations":{},"name":"oauth2-proxy-static-secret","namespace":"oauth2-proxy-app"},"spec":{"destination":{"create":true,"name":"oauth2-proxy-secrets"},"mount":"kv","path":"oauth2-proxy/oidc/admin-apps","refreshAfter":"24h","type":"kv-v2","vaultAuthRef":"oauth2-proxy-vault-auth"}}
    creationTimestamp: "2026-01-27T21:16:24Z"
    finalizers:
    - vaultstaticsecret.secrets.hashicorp.com/finalizer
    generation: 2
    name: oauth2-proxy-static-secret
    namespace: oauth2-proxy-app
    resourceVersion: "8697569"
    uid: 83d3b457-a0d6-425b-b95c-3c694c2c1938
  spec:
    destination:
      create: true
      name: oauth2-proxy-secrets
      overwrite: false
      transformation: {}
    hmacSecretData: true
    mount: kv
    path: oauth2-proxy/oidc/admin-apps
    refreshAfter: 24h
    type: kv-v2
    vaultAuthRef: oauth2-proxy-vault-auth
  status:
    conditions:
    - lastTransitionTime: "2026-01-28T19:40:34Z"
      message: |-
        Failed to sync the secret, horizon=4.40385893s, err=Error making API request.

        URL: PUT https://vault.fahmed.org:8200/v1/auth/kubernetes/login
        Code: 503. Errors:

        * Vault is sealed
      observedGeneration: 2
      reason: Synced
      status: "False"
      type: SecretSynced
    - lastTransitionTime: "2026-01-28T19:40:39Z"
      message: VaultStaticSecretHealthy
      observedGeneration: 2
      reason: Healthy
      status: "True"
      type: Healthy
    lastGeneration: 2
    secretMAC: F5e7SjF3Z5juZ7TEtMRRkizRITen9rccGfEDS2h87XA=
kind: List
metadata:
  resourceVersion: ""
