apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  annotations: {}
  name: oauth2-proxy-static-secret
  namespace: oauth2-proxy-app
spec:
  destination:
    create: true
    name: oauth2-proxy-secrets
  mount: kv
  path: oauth2-proxy/oidc/admin-apps
  refreshAfter: 24h
  type: kv-v2
  vaultAuthRef: oauth2-proxy-vault-auth
