apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
  name: jellyfin-certificate
  namespace: jellyfin-app
spec:
  commonName: jellyfin.fahmed.org
  dnsNames:
    - jellyfin.fahmed.org
  duration: 2160h
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-cloudflare-prod
  renewBefore: 720h
  secretName: jellyfin-tls
