images:
  jellyfin:
    repository: "jellyfin/jellyfin"
    tag: 10.11.11
resources:
  jellyfin:
    requests:
      cpu: 2
      memory: 2Gi
    limits:
      cpu: 4
      memory: 4Gi
      nvidia.com/gpu: 1

jellyfin:
  #extraDevices:
  #  - /dev/nvidia0
  extraDevices:
    - /dev/nvidia0
    - /dev/nvidiactl
    - /dev/nvidia-uvm
  mediaVolumes:
    - name: media-share
      readOnly: false
      volumeSpec:
        accessModes:
          - ReadWriteMany
        capacity:
          storage: 18000Gi
        nfs:
          path: /export/media-share/media
          server: 192.168.1.11
