apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cluster-storage-downloads-pvc
  namespace: qbittorrent-app
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 230Gi
  volumeName: cluster-storage-downloads-pv
  storageClassName: ""
