image:
  name: stakater/reloader
  repository: ghcr.io/stakater/reloader
  tag: v1.4.21
  # digest: sha256:1234567
  pullPolicy: IfNotPresent

reloader:
  watchGlobally: false
  namespaces:
    - vault-app

