---
- name: Config HAProxy and keepalived
  hosts: lbs
  vars:
    ansible_user: ansible
    ansible_pubkey_path: ~/.ssh/ansible.pub
  become: yes
  roles:
    - haproxy_keepalived
    #- firewall

  handlers:
    - name: Restart haproxy
      service:
        name: haproxy
        state: restarted

    - name: Restart keepalived
      service:
        name: keepalived
        state: restarted
