---
- name: Setup K3S Servers
  hosts: k3s_servers
  vars:
    ansible_user: ansible
    server_group: k3s_servers # noqa var-naming[no-role-prefix]
    k3s_version: v1.34.1+k3s1
    api_endpoint: 192.168.100.5
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
    server_config_yaml: |
      tls-san:
        - 192.168.50.4
        - 192.168.100.5
        - 192.168.100.6
        - 192.168.100.7
  become: yes
  roles:
    - k3s_server
    #- firewall

- name: Setup K3S Agents
  hosts: k3s_agents
  vars:
    ansible_user: ansible
    server_group: k3s_servers # noqa var-naming[no-role-prefix]
    k3s_version: v1.34.1+k3s1
    api_endpoint: 192.168.50.4
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
  become: yes
  roles:
    - k3s_agent
    #- firewall
