---
- name: Setup K3S Servers
  hosts: k3s_servers_test
  vars:
    server_group: k3s_servers_test # noqa var-naming[no-role-prefix]
    ansible_user: ansible
    k3s_version: v1.34.1+k3s1
    api_endpoint: 192.168.150.5
    tls_san: 192.168.150.4
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
  become: yes
  roles:
    - k3s_server
    #- firewall

- name: Setup K3S Agents
  hosts: k3s_agents_test
  vars:
    server_group: k3s_servers_test # noqa var-naming[no-role-prefix]
    ansible_user: ansible
    k3s_version: v1.34.1+k3s1
    api_endpoint: 192.168.150.4
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
  become: yes
  roles:
    - k3s_agent
    #- firewall
