image:
  tag: 12.4.0
env:
  GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET:
    valueFrom:
      secretKeyRef:
        name: grafana-secrets
        key: client-secret
admin:
  existingSecret: grafana-secrets
  userKey: user
  passwordKey: password
initChownData:
  enabled: true
persistence:
  enabled: true
grafana.ini:
  auth.generic_oauth:
    enabled: true
  paths:
    data: /var/lib/grafana/
    logs: /var/log/grafana
    plugins: /var/lib/grafana/plugins
    provisioning: /etc/grafana/provisioning
  analytics:
    check_for_updates: true
  log:
    mode: console
  server:
    domain: "{{ if (and .Values.ingress.enabled .Values.ingress.hosts) }}{{ tpl (.Values.ingress.hosts | first) . }}{{ else if (and .Values.route.main.enabled .Values.route.main.hostnames) }}{{ tpl (.Values.route.main.hostnames | first) . }}{{ else }}''{{ end }}"
  unified_storage:
    index_path: /var/lib/grafana-search/bleve
