apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
  name: grafana-sa
  namespace: grafana-app
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultAuth
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
  name: grafana-vault-auth
  namespace: grafana-app
spec:
  kubernetes:
    audiences:
      - vault
    role: grafana-role
    serviceAccount: grafana-sa
  method: kubernetes
  mount: kubernetes
