apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
  name: grafana-static-secret
  namespace: grafana-app
spec:
  destination:
    create: true
    name: grafana-secrets
  mount: kv
  path: grafana
  refreshAfter: 24h
  type: kv-v2
  vaultAuthRef: grafana-vault-auth
