apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  annotations: {}
  name: homarr
  namespace: homarr-app
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`apps.fahmed.org`)
      middlewares: null
      services:
        - name: homarr
          port: 7575
  tls:
    secretName: homarr-tls
