image:
  tag: v1.60.0
database:
  type: postgresql
envSecrets:
  authOidcCredentials:
    existingSecret: homarr-secrets
    oidcClientId: oidc-id
    oidcClientSecret: oidc-secret
  dbCredentials:
    existingSecret: homarr-secrets
    dbUrlKey: db-string
  dbEncryption:
    existingSecret: homarr-secrets
    key: db-encryption
persistence:
  homarrDatabase:
    enabled: false
env:
  TZ: America/Los_Angeles
  ADMIN_GROUP: "/homarr-admins"
  AUTH_PROVIDERS: oidc
  # -- Issuer URI of OIDC provider without trailing slash (/)
  AUTH_OIDC_ISSUER: https://auth.fahmed.org/realms/master
  # -- Display name of provider (in login screen)
  AUTH_OIDC_CLIENT_NAME: Keycloak
  # -- Automatically redirect to OIDC login
  AUTH_OIDC_AUTO_LOGIN: false
  # -- Override the OIDC scopes
  AUTH_OIDC_SCOPE_OVERWRITE: "openid email profile groups"
  # -- Attribute used for groups (roles) claim
  AUTH_OIDC_GROUPS_ATTRIBUTE: "groups"
  # -- Overwrite name attribute. By default, it will use preferred_username if it does not contain a @ and otherwise name.
  #AUTH_OIDC_NAME_ATTRIBUTE_OVERWRITE: 
