image:
  tag: v1.56.0
env:
  TZ: America/Los_Angeles
database:
  type: postgresql
envSecrets:
  dbCredentials:
    existingSecret: homarr-secrets
    dbUrlKey: db-string
  dbEncryption:
    existingSecret: homarr-secrets
    key: db-encryption
persistence:
  homarrDatabase:
    enabled: false
