apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
  name: homarr-oidc-static-secret
  namespace: homarr-app
spec:
  destination:
    create: true
    name: homarr-secrets
  mount: kv
  path: homarr
  refreshAfter: 24h
  type: kv-v2
  vaultAuthRef: homarr-vault-auth
