apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultDynamicSecret
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
  name: keycloak-dynamic-secret
  namespace: keycloak-app
spec:
  destination:
    create: true
    name: keycloak-secrets
  mount: prod-postgres
  path: creds/prod-keycloak-role
  rolloutRestartTargets:
    - kind: StatefulSet
      name: keycloak
  vaultAuthRef: keycloak-dynamic-auth
