apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
  name: vault-tls
  namespace: vault-app
spec:
  commonName: vault.fahmed.org
  dnsNames:
    - vault.fahmed.org
  duration: 2160h
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-cloudflare-prod
  renewBefore: 720h
  secretName: vault-server-tls
