[proxmox_nodes]
proxmox1
proxmox2
proxmox3

[proxmox_nodes:vars]
ansible_ssh_common_args='-o StrictHostKeyChecking=no'

[bastion]
bastion

[pihole]
pihole

[pb_bastion:vars]
ansible_user=root
ansible_ssh_private_key_file=~/.ssh/ansible_proxmox
ansible_ssh_common_args='-o StrictHostKeyChecking=no'
ansible_pubkey_path=~/.ssh/ansible_proxmox.pub

[lbs]
192.168.50.2 state=MASTER priority=200
192.168.50.3 state=BACKUP priority=100

[k3s:children]
k3s_servers
k3s_agents
k3s_servers_test
k3s_agents_test

[k3s_servers]
192.168.100.5
192.168.100.6
192.168.100.7

[k3s_agents]
192.168.100.8
#192.168.100.9
192.168.100.10
192.168.100.11
192.168.100.12
192.168.100.13
192.168.100.14

[k3s_nvidia_nodes]
192.168.100.13

[postgresql]
192.168.200.2

#Add entries when relevant
[k3s_servers_test]
[k3s_agents_test]

[k3s:vars]
ansible_user=default
ansible_ssh_private_key_file=~/.ssh/ansible_proxmox
ansible_ssh_common_args='-o ProxyJump=bastion -o StrictHostKeyChecking=no'
ansible_pubkey_path=~/.ssh/ansible.pub

[pb_lbs:children]
lbs

[pb_lbs:vars]
ansible_ssh_private_key_file=~/.ssh/ansible_proxmox
ansible_ssh_common_args='-o ProxyJump=bastion -o StrictHostKeyChecking=no'
ansible_pubkey_path=~/.ssh/ansible.pub
