[bastion]
#bastion ansible_host=192.168.1.100 ansible_user=ansible ansible_ssh_private_key_file=~/.ssh/ansible_proxmox
192.168.1.2

[targets]
192.168.1.100

[vlan_targets]
192.168.100.10 #vlan 100 target
192.168.100.12

[bastion:vars]
ansible_pubkey_path=~/.ssh/ansible_proxmox.pub

[targets:vars]
ansible_pubkey_path=~/.ssh/infra_global.pub

[vlan_targets:vars]
ansible_pubkey_path=~/.ssh/infra_global.pub

[loadbalancers]
haproxy_lb_01 ansible_host=192.168.68.70 ansible_user=root state=MASTER priority=200 ansible_ssh_private_key_file=~/.ssh/ansible_proxmox
