[proxmox_nodes]
proxmox1
proxmox2
proxmox3

[proxmox_nodes:vars]
ansible_ssh_common_args='-o StrictHostKeyChecking=no'

# pb = pre-boostrapped
[pb_bastion]
# make sure to clear this entry in ~/.ssh/known_hosts
192.168.1.2

[pb_bastion:vars]
ansible_user=root
ansible_ssh_private_key_file=~/.ssh/ansible_proxmox
ansible_ssh_common_args='-o StrictHostKeyChecking=no'
ansible_pubkey_path=~/.ssh/ansible_proxmox.pub

[lbs]
192.168.100.2 state=MASTER priority=200
192.168.100.3 state=BACKUP priority=100

[k3s:children]
k3s_servers
k3s_agents

[k3s_servers]
192.168.100.5
192.168.100.6
192.168.100.7

[k3s_agents]
192.168.100.8
192.168.100.9
192.168.100.10
192.168.100.11
192.168.100.12
192.168.100.13
192.168.100.14

[k3s_test:children]
k3s_servers_test
k3s_agents_test

[k3s_servers_test]
192.168.150.5
192.168.150.6
192.168.150.7

[k3s_agents_test]
192.168.150.14

[k3s:vars]
ansible_user=default
ansible_ssh_private_key_file=~/.ssh/ansible_proxmox
ansible_ssh_common_args='-o ProxyJump=bastion -o StrictHostKeyChecking=no'
ansible_pubkey_path=~/.ssh/infra_global.pub

[pb_lbs:children]
lbs

[pb_lbs:vars]
ansible_ssh_private_key_file=~/.ssh/ansible_proxmox
ansible_ssh_common_args='-o ProxyJump=bastion -o StrictHostKeyChecking=no'
ansible_pubkey_path=~/.ssh/infra_global.pub

[targets]
#pihole
192.168.68.102
#192.168.1.100

[targets:vars]
ansible_pubkey_path=~/.ssh/infra_global.pub
