apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
  name: sonarr-certificate
  namespace: sonarr-app
spec:
  commonName: sonarr.fahmed.org
  dnsNames:
    - sonarr.fahmed.org
  duration: 2160h
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-cloudflare-prod
  renewBefore: 720h
  secretName: sonarr-tls
