apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cluster-storage-pvc-root-sonarr
  namespace: sonarr-app
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 18000Gi
  volumeName: cluster-storage-pv-root-sonarr
  storageClassName: ""
