apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  annotations: {}
  name: traefik
  namespace: kube-system
spec:
  valuesContent: |-
    providers:
      kubernetesCRD:
        allowCrossNamespace: true

    ports:
      web:
        forwardedHeaders:
          trustedIPs:
            - 10.0.0.0/8

    persistence:
      enabled: true
